linear_method_srcs = \
linear_method.cc computation_node.cc scheduler.cc \
batch_scheduler.cc batch_server.cc batch_worker.cc \
darlin_scheduler.cc darlin_server.cc darlin_worker.cc \
lrl1_scheduler.cc lrl1_server.cc lrl1_worker.cc \
lrl2_scheduler.cc lrl2_server.cc lrl2_worker.cc \
countlrl1_scheduler.cc countlrl1_server.cc countlrl1_worker.cc \
ftrl_scheduler.cc ftrl_worker.cc \

#smooth_scheduler.cc smooth_server.cc smooth_worker.cc \
# batch_solver.cc darling.cc
